
POST http://localhost:9000/user/register
Content-Type: application/json

{
    "name":"Edu",
    "last_name":"Caubilla",
    "email":"edu@mail.com",
    "password":"1234"
}


########################


POST http://localhost:9000/user/login
Content-Type: application/json

{
    "email":"edu@mail.com",
    "password":"1234"
}

